name: Deploy HyperLeap Website

on:
  push:
    branches: [ "main" ]        
  pull_request:
    branches: [ "main" ]    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Run W3C HTML Validator
        run: |
          npm install -g w3c-html-validator
          w3c-html-validator src/index.html

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: |
            kinefall/hyperleap-web:latest
            kinefall/hyperleap-web:${{ github.sha }}
      
      - name: Set image tag output
        id: set-tag
        run: echo "image-tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy-staging:
    needs: build-and-push            
    runs-on: ubuntu-latest
    environment: staging             
    steps:
      - name: Deploy staging on :8080
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          debug: true
          - name: Add host key (safe SSH)
            run: |
               mkdir -p ~/.ssh
               ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
               chmod 600 ~/.ssh/known_hosts
          script: |
            set -x
            sudo systemctl start docker
            sudo docker pull kinefall/hyperleap-web:${{ needs.build-and-push.outputs.image-tag }}
            sudo docker stop hyperleap-staging || true
            sudo docker rm hyperleap-staging || true
            sudo docker run -d --restart unless-stopped --name hyperleap-staging -p 8080:80 \
              kinefall/hyperleap-web:${{ needs.build-and-push.outputs.image-tag }}
            # smoke test
            sleep 3
            curl -sSf http://localhost:8080 >/dev/null


  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: deploy-staging           
    runs-on: ubuntu-latest
    environment:
      name: production               
    steps:
      - name: Deploy production on :80
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          debug: true
          - name: Add host key (safe SSH)
            run: |
               mkdir -p ~/.ssh
               ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
               chmod 600 ~/.ssh/known_hosts
          script: |
            set -x
            sudo systemctl start docker
            sudo docker pull kinefall/hyperleap-web:${{ needs.build-and-push.outputs.image-tag }}
            sudo docker stop hyperleap-prod || true
            sudo docker rm hyperleap-prod || true
            sudo docker run -d --restart unless-stopped --name hyperleap-prod -p 80:80 \
              kinefall/hyperleap-web:${{ needs.build-and-push.outputs.image-tag }}
            # smoke test
            sleep 3
            curl -sSf http://localhost >/dev/null
